service: serverless-t5-lambda-docker

provider:
  name: aws # provider
  region: eu-west-1 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

functions:
  questionanswering:
    image: 402336464871.dkr.ecr.eu-west-1.amazonaws.com/t5-summarizer:latest #ecr url
    events:
      - http:
          path: qa # http path
          method: post # http method
