service: serverless-t5-lambda-docker

provider:
  name: aws # provider
  region: eu-west-1 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 180 # optional, in seconds, default is 6

functions:
  summarizer:
    image: 402336464871.dkr.ecr.eu-west-1.amazonaws.com/t5-summarizer@sha256:58dfaf99e5d9f4530833bc2531bfefa02e5c581a902690dfefce2cf534ebfefd #ecr url
    events:
      - http:
          path: summarize # http path
          method: post # http method
          async: true
